In [55]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [56]:
df = sns.load_dataset('iris')

In [57]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [58]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X = df.drop('species',axis=1)
y = df['species']

In [61]:
X_train , X_test , Y_train , Y_test = train_test_split(X,y,random_state=42,test_size=.20)

In [62]:
from sklearn.neighbors import KNeighborsClassifier

In [63]:
model = KNeighborsClassifier(n_neighbors=10)

In [64]:
model.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=10)

In [65]:
model.score(X_test,Y_test)

1.0

In [66]:
from sklearn.svm import SVC

In [88]:
model_SVM = SVC(gamma='auto')

In [89]:
model_SVM.fit(X_train,Y_train)

SVC(gamma='auto')

In [90]:
model.score(X_test,Y_test)

1.0

## grid serch CV

In [91]:
from sklearn.model_selection import GridSearchCV

In [120]:
Classifier = GridSearchCV((model_SVM),{
    'C':[1,3,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [121]:
Classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 3, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [122]:
Classifier.cv_results_

{'mean_fit_time': array([0.00098844, 0.00085068, 0.00071821, 0.00053921, 0.00065742,
        0.0005394 , 0.00057082, 0.00063839, 0.00059929, 0.00054679]),
 'std_fit_time': array([2.76602767e-04, 2.62993006e-04, 1.80560332e-04, 2.26508191e-05,
        1.29535304e-04, 2.21483546e-05, 2.46789834e-05, 2.35884773e-04,
        4.04133487e-05, 1.25523250e-05]),
 'mean_score_time': array([0.00062065, 0.00061955, 0.00067759, 0.00038037, 0.00042715,
        0.00037808, 0.00040641, 0.00040226, 0.00041614, 0.00038109]),
 'std_score_time': array([1.00108370e-04, 2.91047847e-04, 4.75083440e-04, 1.24891289e-06,
        2.98027420e-05, 4.11684755e-06, 2.31217350e-05, 4.71836091e-05,
        1.13248574e-05, 8.17549788e-06]),
 'param_C': masked_array(data=[1, 1, 3, 3, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 3, 'kernel': 'rbf'},
  {'C': 3, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        1.        , 0.96666667, 1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 0.96666667,
        0.9       , 0.9       , 0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.97333333, 0.97333333, 0.98      ,
        0.97333333, 0.96666667, 0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.02494438, 0.02494438, 0.01632993,
        0.03887301, 0.03651484, 0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 4, 4, 1, 4, 7, 8, 9, 9], dtype=int32)}

In [123]:
result = pd.DataFrame(Classifier.cv_results_)

In [124]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000988,0.000277,0.000621,0.000100,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000851,0.000263,0.000620,0.000291,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000718,0.000181,0.000678,0.000475,3,rbf,"{'C': 3, 'kernel': 'rbf'}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,4
3,0.000539,0.000023,0.000380,0.000001,3,linear,"{'C': 3, 'kernel': 'linear'}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,4
4,0.000657,0.000130,0.000427,0.000030,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.000539,0.000022,0.000378,0.000004,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
6,0.000571,0.000025,0.000406,0.000023,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,7
7,0.000638,0.000236,0.000402,0.000047,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,8
8,0.000599,0.000040,0.000416,0.000011,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,9
9,0.000547,0.000013,0.000381,0.000008,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,9

In [125]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2        3          rbf         0.973333
3        3       linear         0.973333
4       10          rbf         0.980000
5       10       linear         0.973333
6       20          rbf         0.966667
7       20       linear         0.966667
8       30          rbf         0.960000
9       30       linear         0.960000

## RandomizedSearchCV

In [127]:
from sklearn.model_selection import RandomizedSearchCV

In [173]:
Classifier_2= RandomizedSearchCV((model_SVM),{
    'C':[1,3,5,10,20],
    'kernel':['rbf','linear']
},n_iter=13,cv=5, return_train_score=False)

In [174]:
Classifier_2.fit(X,y)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 10 is smaller than n_iter=13. Running 10 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=13,
                   param_distributions={'C': [1, 3, 5, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [175]:

pd.DataFrame(Classifier_2.cv_results_)[['param_kernel','mean_test_score','param_C']]

  param_kernel  mean_test_score  param_C
0          rbf         0.980000        1
1       linear         0.980000        1
2          rbf         0.973333        3
3       linear         0.973333        3
4          rbf         0.980000        5
5       linear         0.980000        5
6          rbf         0.980000       10
7       linear         0.973333       10
8          rbf         0.966667       20
9       linear         0.966667       20